#-------------------------------
# General Site Settings
title: Nitin B. Ravi
logo: # You can add own logo.
description: Personal Webpage of Nitin B. Ravi

#-------------------------------
# Author Settings
author:
  name: Nitin B. Ravi
  image: ProfilePic.jpg
  #say-hello: Hello, I’m <strong>Nitin</strong>
  bio: Researcher, Tech-buff, Sustainable living advocate, Animal lover &amp; Adoption advocate.

#-------------------------------
# Contact links
twitter: https://twitter.com/nitinbravi # Add your Twitter handle
linkedin: http://www.linkedin.com/in/nitinbalajee
instagram: https://instagram.com/nitinbrav # Add your Instagram handle


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: UA-92185184-1 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
#mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
