#-------------------------------
# General Site Settings
title: Nitin B. Ravi
logo: # You can add own logo.
description: Personal Webpage of Nitin B. Ravi

#-------------------------------
# Author Settings
author:
  name: Nitin B. Ravi
  image: ProfilePic.jpg
  #say-hello: Hello, I’m <strong>Nitin</strong>
  bio: Researcher, Tech-buff, Sustainable Living, Animal Lover, Adoption advocate.

#-------------------------------
# Contact links
twitter: https://twitter.com/nbr2488 # Add your Twitter handle
linkedin: http://www.linkedin.com/in/nitinbalajee
#facebook: https://facebook.com/ # Add your Facebook handle
#dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/nitinbrav # Add your Instagram handle
#pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
#disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: nitinbrav # Add instagram username


#-------------------------------
# Google Analytics
# google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
#mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
